/**
 * Generated by orval v6.2.4 🍺
 * Do not edit manually.
 * Covid Test Management
 * OpenAPI spec version: 1.0
 */
import {
  rest
} from 'msw'
import faker from 'faker'

export const getPostApiV1LoginMock = () => ({userId: faker.helpers.randomize([faker.random.word(), undefined])})

export const getCovidTestManagementMSW = () => [
rest.get('*/api/v1/Center', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
        )
      }),rest.get('*/api/v1/Hello', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
        )
      }),rest.post('*/api/v1/Login', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.text(getPostApiV1LoginMock()),
        )
      }),]
